import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Provider from "./StoreProvider";
import Footer from "./footer";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hant-TW">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex flex-col px-[12px] min-h-[calc(100vh-30px)] w-[1280px] max-w-[100vw] mx-auto bg-[#f9f9f9] dark:bg-[#1a1a1a] text-[#111] dark:text-[#f9f9f9]">
          <Provider>{children}</Provider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
